"""Persist UI-supplied model credentials for future backend processes."""

from __future__ import annotations

import json
import os
from enum import Enum
from pathlib import Path

from app.config.setting import Settings, USER_CONFIG_PATH


_AGENT_PREFIXES = (
    "COORDINATOR",
    "MODELER",
    "CODER",
    "WRITER",
    "MODEL_SCOUT",
    "MODEL_CRITIC",
)
_AGENT_SUFFIXES = (
    "API_TYPE",
    "API_KEY",
    "MODEL",
    "BASE_URL",
    "CONTEXT_WINDOW",
)


def _dotenv_value(value: object) -> str:
    if isinstance(value, Enum):
        value = value.value
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)


def persist_user_config(
    config: Settings,
    path: Path = USER_CONFIG_PATH,
) -> Path:
    """Atomically write effective UI-editable settings without logging secrets."""
    keys = [
        f"{prefix}_{suffix}" for prefix in _AGENT_PREFIXES for suffix in _AGENT_SUFFIXES
    ]
    keys.extend(["MODEL_COUNCIL_ENABLED", "OPENALEX_EMAIL"])

    lines = [
        "# Remit user configuration. Generated by the settings dialog.",
        "# Contains API credentials; do not share this file.",
    ]
    for key in keys:
        value = getattr(config, key, None)
        if value is None or (isinstance(value, str) and not value.strip()):
            continue
        lines.append(f"{key}={_dotenv_value(value)}")

    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f"{path.name}.tmp")
    try:
        temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
        try:
            os.chmod(temporary, 0o600)
        except OSError:
            pass
        os.replace(temporary, path)
    finally:
        try:
            temporary.unlink(missing_ok=True)
        except OSError:
            pass
    return path
